FROM node:20-alpine

WORKDIR /app

COPY docker/services/express/package*.json .

RUN npm install

COPY docker/services/express/* .

EXPOSE 3000

CMD ["npm", "run", "express"]

# for diagnosing container
# CMD ["sh", "-c", "tail -F keep_alive"]