FROM node:20-alpine

WORKDIR /app

COPY ./docker/services/express/package*.json .

RUN npm install

COPY . .

# CMD ["npm", "run", "express:debug"]

# // for diagnosing container
CMD ["sh", "-c", "tail -F keep_alive"]