ALTER TABLE cards
ADD COLUMN external_id VARCHAR(255) DEFAULT NULL,
ADD COLUMN type VARCHAR(255) DEFAULT NULL,
ADD COLUMN network VARCHAR(255) DEFAULT NULL,
ADD COLUMN country VARCHAR(255) DEFAULT NULL,
ADD COLUMN bank_name VARCHAR(255) DEFAULT NULL;